version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  accountingdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4 
    
volumes:
  postgres_data:
  pgadmin_data: